language: python
sudo: false
cache: pip

python:
  - "3.5"
  - "3.6"

matrix:
  include:
    # Python 3.7 workaround
    - python: 3.7.4
      dist: xenial
      sudo: true

install:
  - pip install -U pylava
  - pip install -e .
  - pip install -U -r .readthedocs/requirements.txt

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  # Linting
  - pylama .

  # Coverage & unit tests
  - coverage run setup.py test
  - coverage combine
  - coverage report -i

  # Build docs
  - cd docs && make html

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
